# Generated by Django 3.1 on 2022-06-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220604_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
    ]
